### ISSUE TITLE
Error with wout VMEC=8.0 and undefined xm_nyq

### ISSUE THREAD

**Issue by RalfMackenbach** [lazersos/matlabVMEC#3]
Hi Sam,

I'm trying to read a older VMEC=8.0 file (attached below). Whilst calling read_vmec, the following error pops up

```
Unrecognized field name "xm_nyq".
Error in read_vmec>half2fullmesh (line 2227)
dexe = mod(f.xm_nyq,2)==0;
Error in read_vmec (line 129)
f=half2fullmesh(f); 
```

After looking around the code for a bit, it seems this variable is indeed not defined in `read_vmec_800(fid,fmt)`. I did not have much luck fixing it; any tips?

[wout_Mikhailov.txt](https://github.com/lazersos/matlabVMEC/files/8364598/wout_Mikhailov.txt)

**Comment by lazersos** [comment]
@RalfMackenbach I've updated the code to more properly deal with this.  However, I must warn you that if a VMEC wout file is generated in this way, then care must be taken with the B-field.  The R, Z, and Lambda arrays will be fine, but any quantity which is derived from the Jacobian (sqrt(g)) will possibly have errors.  One way to handle this it to run with `MPOL` and `NTOR` much larger than mode spectrum in the boundary harmonics.  However, this can make force descent difficult.

Let me know if the recently pushed fix helps and I'll close the issue.

**Comment by RalfMackenbach** [comment]
Helps, thanks!
